configName: sam_e70_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: ATSAME70Q21B
projectName: ''
settings:
  PackageFilter: bsp;classb_sam_e70_s70_v70_v71;core;core_apps_sam_e70_s70_v70_v71;crypto;csp;csp_apps_sam_e70_s70_v70_v71;dev_packs;gfx;gfx_apps_sam_e70_s70_v70_v71;net_apps_sam_e70_v71;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.6.98\same70b\atdf\ATSAME70Q21B.atdf
